[workspace]
members = [
	"gaben",
	"sdk",
	"macros", "installer",
]

[workspace.dependencies]
derive-getters = "0.3.0"
derive_builder = "0.20.0"
log = "0.4.21"
env_logger = "0.11.3"
strum = "0.26.2"
strum_macros = "0.26.2"

