[config]
default_to_workspace = false

[tasks.dump]
script = "python ./scripts/dump-offsets.py"

[tasks.dummy]
script = "rustc \"$($PWD.Path)\\external\\program.rs\" -C opt-level=3"

[tasks.bait]
command = "cargo"
args = ["build", "--bin", "gaben", "--release"]

[tasks.pdm]
command = "cargo"
args = ["build", "--bin", "pdm", "--release"]

[tasks.build-debug]
script = '''
cargo build --bin gaben
cargo build --bin pdm
'''

[tasks.build]
dependencies = [
	"bait",
	"pdm"
]
